/**
 * Run the outbound campaign unattended, on an autonomous project.
 *
 * The interactive path paces itself from the browser, which is fine while
 * someone is watching and useless on a schedule. Here the pace comes from the
 * cycle itself: a handful per run, spaced out, and the next run picks up where
 * this one stopped. Nothing is lost by stopping early - the pending list is
 * derived from what has already been recorded.
 */
import { eq } from "drizzle-orm";
import { db, projects, supplierLeads } from "../db";
import {
  MAX_DISCOVERY_RUNS,
  reenrichMissing,
  runDiscovery,
  TARGET_LEADS,
  usableLeadCount,
} from "../discovery/run";
import { approveAllAbove } from "../actions/discovery";
import { campaignStatus, prepareCampaign, sendNext } from "./batch";
import { buildOutreachEmail } from "./template";
import { getSettings } from "../settings";
import { items, requirements } from "../db";
import { asc } from "drizzle-orm";
import { claimSlot, mayStartOutreach, releaseSlot } from "./slot";

/**
 * Enough to make progress every couple of hours, few enough that a mistake is
 * caught before it reaches a whole shortlist. Three was too cautious once the
 * target became thirty: at three every two hours a full shortlist takes most
 * of a day to write to, and the pacing that matters to a supplier is the gap
 * between messages, not how many other factories heard from us today.
 */
const MAX_PER_RUN = 6;

/** How long one cycle may spend searching before it moves on. */
const DISCOVERY_BUDGET_MS = 70_000;

/**
 * Seconds between sends inside one run.
 *
 * It was 25-45s, which at six sends is nearly four minutes of a cycle that has
 * under three - the pause alone would decide how many suppliers got written to.
 * The gap is there so a shortlist does not arrive as one visible blast, and
 * eight to twenty seconds does that: these are separate emails to separate
 * companies, and a person working through a sourcing list sends them about
 * this fast.
 */
function pauseMs(): number {
  return 8_000 + Math.floor(Math.random() * 12_000);
}

export interface CampaignRun {
  sent: string[];
  failed: { company: string; error: string }[];
  remaining: number;
  skipped: string | null;
}

export async function runCampaign(
  projectId: string,
  options: { deadline?: number } = {},
): Promise<CampaignRun> {
  const deadline = options.deadline ?? Date.now() + 150_000;
  const [project] = await db.select().from(projects).where(eq(projects.id, projectId));
  if (!project) return { sent: [], failed: [], remaining: 0, skipped: "no project" };

  if (project.autonomyTier < 3) {
    return { sent: [], failed: [], remaining: 0, skipped: "not autonomous" };
  }

  /*
   * Write the outreach email if nobody has.
   *
   * This was the real reason Ceiling Curtain Track never sent: it had
   * twenty-eight approved suppliers, a full shortlist and permission to write,
   * and no email to send them. `prepareCampaign` threw "no saved email for this
   * project" every cycle, the error was recorded against the project, and the
   * summary line still said the campaign was fine.
   *
   * The draft is generated by the page when somebody opens the project - which
   * makes an autonomous project depend on being looked at. Nothing in it is a
   * decision; it is built from the RFQ that was already parsed, which is the
   * same reason parsing and discovery run unattended.
   */
  if (!project.outreachBody || !project.outreachSubject) {
    const [projectItems, projectRequirements, settings] = await Promise.all([
      db.select().from(items).where(eq(items.projectId, projectId)).orderBy(asc(items.name)),
      db.select().from(requirements).where(eq(requirements.projectId, projectId)),
      getSettings(),
    ]);

    if (projectItems.length > 0) {
      const { subject, body } = buildOutreachEmail(project, projectItems, projectRequirements, {
        name: settings.senderName,
        title: settings.senderTitle,
      });

      await db
        .update(projects)
        .set({ outreachSubject: subject, outreachBody: body })
        .where(eq(projects.id, projectId));

      project.outreachSubject = subject;
      project.outreachBody = body;
    }
  }

  /*
   * Approve first, because it is free.
   *
   * A database update with no model call and no network, so it costs nothing to
   * do before deciding whether there is time for anything else - and without it
   * a lead scored on the last cycle would not be sendable on this one.
   */
  const approval = new FormData();
  approval.set("projectId", projectId);
  approval.set("threshold", "30");
  await approveAllAbove({}, approval);

  const status = await campaignStatus(projectId);
  const run: CampaignRun = {
    sent: [],
    failed: [],
    remaining: status.pending.length,
    skipped: null,
  };

  /*
   * A project that finished and has since found more suppliers goes back in
   * the queue rather than staying finished forever.
   *
   * Discovery keeps running after the first round of outreach, so new approved
   * leads appear on a project that has already released the slot. Without this
   * they would sit as recipients nobody was allowed to write to: the gate
   * answers "everyone has already been contacted", which was true when it was
   * stamped and is not any more. Re-queuing means they are paced like any
   * other cold batch, which is the right treatment - they are exactly that.
   */
  if (project.outreachCompletedAt) {
    await db
      .update(projects)
      .set({ outreachStartedAt: null, outreachCompletedAt: null })
      .where(eq(projects.id, projectId));
  }

  /*
   * The pacing gate. Everything above this line is preparation - searching,
   * enriching, approving - and none of it writes to anybody, so it runs whether
   * or not this project's turn has come. Only the sending waits.
   */
  const slot = status.pending.length > 0 ? await mayStartOutreach(projectId) : null;

  /*
   * Nothing to send is not a reason to stop.
   *
   * Both of these used to return early, and both skipped everything after them
   * - which now includes the search. A project that has written to all nineteen
   * of its suppliers and needs eleven more would never look for them again, and
   * a project waiting its turn would sit still instead of getting its list
   * ready for when the turn came. Falling through costs nothing and is the
   * whole point of the time left over.
   */
  if (status.pending.length === 0) {
    await releaseSlot(projectId);
  } else if (slot && !slot.may) {
    run.skipped = slot.reasonHe;
  }

  if (slot?.may) {
    await claimSlot(projectId);

    // Fails loudly here rather than half way through a list: a missing
    // walk-away or an unset mailbox should stop the run, not produce three
    // sends and a crash on the fourth.
    const prepared = await prepareCampaign(projectId);

    /*
     * Bounded by what is left of the day, not by a private allowance. The
     * budget is shared, so a project that finds room for four sends four and
     * the next project takes whatever survives.
     */
    const allowedNow = Math.min(MAX_PER_RUN, slot.remaining);

    for (let i = 0; i < allowedNow; i++) {
      if (Date.now() > deadline) break;

      const outcome = await sendNext(projectId, prepared);
      if (!outcome) break;

      if (outcome.ok) {
        run.sent.push(outcome.recipient.companyName);
      } else {
        run.failed.push({
          company: outcome.recipient.companyName,
          error: outcome.error ?? "",
        });
      }

      run.remaining = outcome.remaining;
      if (outcome.remaining === 0) {
        await releaseSlot(projectId);
        break;
      }
      if (i < allowedNow - 1) await new Promise((resolve) => setTimeout(resolve, pauseMs()));
    }
  }

  /*
   * Searching happens after sending, with whatever time is left.
   *
   * It used to run first, and that was the wrong way round in a way the cycle
   * made expensive: discovery took up to seventy seconds, re-enrichment took
   * more, and the deadline is shared across every project in the cycle - so
   * Ceiling Curtain Track, with twenty-eight suppliers waiting and permission
   * to write to eleven of them, reached the send loop with no time left and
   * sent nothing. Three cycles in a row.
   *
   * Sending is the point. Searching feeds future sending and can always wait a
   * cycle; the reverse is not true, because a day's unsent allowance does not
   * come back.
   */
  /*
   * Counted the same way the search counts it, which it was not.
   *
   * This gate used the raw number of stored leads while the target inside the
   * search means leads with an address and a passing score. A project holding
   * thirty-two rows of which nineteen were usable read as finished, and three
   * of five projects had quietly stopped searching short of their target with
   * nothing on the page to say so.
   */
  const usable = await usableLeadCount(projectId);
  const timeLeft = deadline - Date.now();

  if (
    timeLeft > 25_000 &&
    usable < TARGET_LEADS &&
    (project.discoveryRuns ?? 0) < MAX_DISCOVERY_RUNS
  ) {
    await runDiscovery(projectId, {
      maxRounds: 4,
      deadline: Math.min(Date.now() + DISCOVERY_BUDGET_MS, deadline - 10_000),
    });
  }

  // Another go at the leads with no address, if anything is still left.
  if (deadline - Date.now() > 20_000) {
    await reenrichMissing(projectId, { limit: 8, deadline: deadline - 10_000 });
  }

  return run;
}
